receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://*
            - https://*

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['0.0.0.0:8890'] 


exporters:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp/tempo:
    endpoint: tempo:4007
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8890"

processors:
  attributes:
    actions:
      - key: env
        value: local
        action: insert
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch,  attributes]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [batch,  attributes]
      exporters: [prometheus]