#https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  url: http://prometheus:9090
  jsonData:
    timeInterval: 10s
  basicAuth: false
  version: 1
  editable: false

- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  url: http://tempo:3200
  basicAuth: false
  version: 1
  editable: true
  jsonData:
    nodeGraph:
      enabled: true
    tracesToLogsV2:
      datasourceUid: 'loki'
      spanStartTimeShift: '-10m'
      spanEndTimeShift: '10m'
      filterByTraceID: true
      filterBySpanID: false
      customQuery: false

- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  version: 1
  editable: true
  isDefault: true
  jsonData:
    maxLines: 1000
    derivedFields:
    - datasourceUid: tempo
      name: TraceID
      url: $${__value.raw}
      matcherType: "label"
      matcherRegex: "^trace_id$"
      urlDisplayLabel: "View Trace"    